# Generated by Django 3.2 on 2023-05-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230526_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-pk',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-pk',), 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
    ]
