# Generated by Django 3.2 on 2023-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230530_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
