# Generated by Django 3.2 on 2023-06-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
