# Generated by Django 3.2 on 2023-06-05 07:03

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Обязательное поле. Пример: #49B64E', max_length=7, validators=[recipes.validators.ColorHexCodeValidator()], verbose_name='Цветовой HEX-код'),
        ),
    ]
