# Generated by Django 3.2 on 2023-06-06 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20230606_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Обязательное поле', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Обязательное поле', on_delete=django.db.models.deletion.PROTECT, related_name='recipes_with_ing', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
