# Generated by Django 3.2 on 2023-05-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_follow_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('pk',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
