# Generated by Django 3.2 on 2023-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subscribe_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_me_forbidden',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('username', 'me'), ('username', 'igi'), _connector='OR'), _negated=True), name='username_me_forbidden'),
        ),
    ]
