# Generated by Django 3.2 on 2023-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230522_1328'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_me_forbidden',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('username', 'me'), ('username', 'subscriptions'), _connector='OR'), _negated=True), name='forbidden_usernames'),
        ),
    ]
