# Generated by Django 3.2 on 2023-06-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230604_1050'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='forbidden_usernames',
        ),
    ]
